# Generated by Django 3.2.19 on 2023-06-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('extra_phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('info', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
