# Generated by Django 3.2.19 on 2023-06-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('construction_year', models.IntegerField()),
                ('price_per_meter', models.DecimalField(decimal_places=0, max_digits=12)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('area', models.DecimalField(decimal_places=1, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_extra_phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Property type',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses_images/')),
                ('house', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.propertytype'),
        ),
    ]
