# Generated by Django 3.2.19 on 2023-06-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20230628_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.propertytype'),
        ),
    ]
