# Generated by Django 3.2.19 on 2023-06-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('houses', '0003_alter_house_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
    ]
