# Generated by Django 3.2.19 on 2023-06-29 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
        ('houses', '0004_alter_house_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='house',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
